services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter_data:/home/jovyan/work
      - ./jupyter_config:/home/jovyan/.jupyter
    environment:
      - JUPYTER_TOKEN=*****
      - GRANT_SUDO=yes
    restart: unless-stopped
    command: start-notebook.sh --NotebookApp.token='*****' --NotebookApp.password=''
    networks:
      - jupyter-network
    mem_limit: 12g     # Limit to 4GB RAM
    cpus: 2.0         # Limit to 1 full CPU core

networks:
  jupyter-network:
    external: true
    name: npm-bridge
